backend:
  name: git-gateway
  branch: master

publish_mode: 'editorial_workflow'
media_folder: '/files'

collections:
  - name: 'post'
    label: 'News'
    description: 'Posts/News for the site'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Tags', name: 'tags', widget: 'list'}
      - {label: 'Body', name: 'body', widget: 'text'}
  - name: 'pages'
    label: 'Pages'
    description: 'Pages for the site. The permalink is what the URL will be. The "body" accepts markdown (editor) or HTML'
    folder: '_pages'
    create: true
    slug: '{{slug}}'
    identifier_field: 'permalink'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'Language', name: 'language', widget: 'hidden', default: 'en'}
      - {label: 'Permalink', name: 'permalink', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: "settings"
    label: "Settings"
    files:
      - name: "team"
        label: "Team"
        file: "_data/team.yml"
        extension: "yml"
        fields:
          - label: "Team"
            name: "member"
            widget: "list"
            fields:
              - {label: "Identifier", name: "identifier", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "VCard", name: "vcard", widget: "string", required: false}
              - {label: "Photo", name: "photo", widget: "string", required: false}
              - {label: "Qualifications", name: "qualifications", widget: "text", required: false}
              - {label: "Background", name: "background", widget: "text", required: false}
              - {label: "Skills", name: "skills", widget: "text", required: false}
              - {label: "Responsibilities", name: "responsibilities", widget: "text", required: false}
      - name: "library"
        label: "e-library"
        file: "_data/library.yml"
        extension: "yml"
        fields:
          - label: "Issues"
            name: "issue"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Language"
                name: "language"
                widget: "select"
                options:
                  - label: "English"
                    value: "en"
                  - label: "Russian"
                    value: "ru"
              - label: "Types"
                name: "types"
                widget: "select"
                multiple: true
                options:
                  - label: "Tax Updates"
                    value: "tax-update"
                  - label: "Tax Alerts"
                    value: "tax-alert"
                  - label: "Articles"
                    value: "article"
                  - label: "Information Sheets"
                    value: "sheet"
              - label: "Date"
                name: "date"
                widget: "date"
              - label: "File"
                name: "file"
                widget: "file"
