backend:
  name: git-gateway
  branch: master

publish_mode: 'editorial_workflow'
media_folder: '/files'

collections:
  - name: 'post'
    label: 'News'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Tags', name: 'tags', widget: 'list'}
      - {label: 'Body', name: 'body', widget: 'text'}
  - name: 'pages-en'
    label: 'Pages (English)'
    folder: '_en'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'Language', name: 'language', widget: 'hidden', default: 'en'}
      - {label: "Name", name: "name", widget: "string"}
      - {label: 'Permalink', name: 'permalink', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'pages-ru'
    label: 'Pages (Russian)'
    folder: '_ru'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'Language', name: 'language', widget: 'hidden', default: 'ru'}
      - {label: "Name", name: "name", widget: "string"}
      - {label: 'Permalink', name: 'permalink', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'text'}
  - name: "settings"
    label: "Settings"
    files:
      - name: "team"
        label: "Team"
        file: "_data/team.yml"
        extension: "yml"
        fields:
          - label: "Team"
            name: "member"
            widget: "list"
            fields:
              - {label: "Identifier", name: "identifier", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Title", name: "title", widget: "string"}
              - {label: "VCard", name: "vcard", widget: "string", required: false}
              - {label: "Photo", name: "photo", widget: "string", required: false}
              - {label: "Qualifications", name: "qualifications", widget: "text", required: false}
              - {label: "Background", name: "background", widget: "text", required: false}
              - {label: "Skills", name: "skills", widget: "text", required: false}
              - {label: "Responsibilities", name: "responsibilities", widget: "text", required: false}
