backend:
  name: git-gateway
  branch: master

publish_mode: 'editorial_workflow'
media_folder: '/files'

collections:
  - name: 'post'
    label: 'News'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Tags', name: 'tags', widget: 'list'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'pages-en'
    label: 'Pages (English)'
    folder: '_en'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'Language', name: 'language', widget: 'hidden', default: 'en'}
      - {label: 'Permalink', name: 'permalink', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'pages-ru'
    label: 'Pages (Russian)'
    folder: '_ru'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'page'}
      - {label: 'Language', name: 'language', widget: 'hidden', default: 'ru'}
      - {label: 'Permalink', name: 'permalink', widget: 'string'}
      - {label: 'Body', name: 'body', widget: 'markdown'}
  - name: 'our-team'
    label: 'Our Team'
    files:
      - label: 'Team'
        name: 'team'
        file: '_data/team.yml'
        widget: list
        fields:
          - {label: 'Identifier', name: 'identifier', widget: 'string'}
          - {label: 'Name', name: 'name', widget: 'string'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Qualifications', name: 'qualifications', widget: 'markdown'}
          - {label: 'Background', name: 'background', widget: 'markdown'}
          - {label: 'Skills', name: 'skills', widget: 'markdown'}
          - {label: 'Responsibilities', name: 'responsibilities', widget: 'markdown'}
